### ISSUE TITLE
Make the code constant time

### ISSUE THREAD

**Issue by DemiMarie-parity** [algorand/pairing-plus#12]

**Comment by burdges** [comment]
It's being done alongside splitting out the crates more in https://github.com/zkcrypto/bls12_381/ but no idea if and when that crate becomes usable.

**Comment by str4d** [comment]
The `bls12_381` crate is ready and usable on its own in concrete settings. Work is ongoing to refactor the `ff`, `group`, and `pairing` crates so that `bls12_381` (and `jubjub`) can implement their traits.

**Comment by zhenfeizhang** [comment]
Agreed.

For constant time library please use `bls12_381`.
